maximum_length_name: 50
maximum_length_email: 255
minimum_length_pass: 6
gravatar_size: 80
checked: 1
expired_time: 2
address: "Floor, 9, 434 Tran Khat Chan, Hai Ba Trung, Hanoi"
telephone: "098 453 0860"
email_tripbricks: "info@tripbricks.com"
max_hotel_per_page: 5
max_image_per_page: 5
max_room_per_page: 5
